services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: discordclone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/discordclone
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_CONFIG_IMPORT: optional:configtree:/run/secrets/
    secrets:
      - source: db_password
        target: /run/secrets/spring.datasource.password
      # - jwt_secret
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt